version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: viscard-db
    environment:
      POSTGRES_USER: viscard_user
      POSTGRES_PASSWORD: viscard_password
      POSTGRES_DB: viscard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
